import Head from "next/head";
import Image from "next/image";
import React from "react";
import ScaleLoader   from "react-spinners/ScaleLoader";
import styles from "../styles/Home.module.scss";

const Loader = () => {
  return (
    <div className>
      <Head>
        <title>News60</title>
        <meta name="description" content="Generated by create next app" />
      
        <link rel="icon" href="/favicon.png" />
      </Head>
      <nav className={styles.navbar}>
        <Image
          src="/icon.png"
          width={50}
          height={50}
          className={styles.img}
          alt="Logo"
        />
        <h1>News60</h1>
      </nav>
    <div style={{
        display:"flex",
        alignItems:"center",
        justifyContent:"center",
        color:"#0a0d37",
        height:"100vh"
    }}>
      <ScaleLoader   color="#0a0d37" loading  />{" "}
      
    </div>
    </div>
  );
};

export default Loader;
