import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { AiOutlineMenu, AiOutlineClose } from "react-icons/ai";
import { useEffect, useRef, useState } from "react";
import { FetchFromAPI } from "../utils/FetchFromAPI";
import { categories } from "../utils/constants";
import Loader from "../components/Loader";

export default function Home() {
 const [selectedcategory, setSelectedcategory] = useState('All');
  const [data, setData] = useState();
  useEffect(() => {
    FetchFromAPI(selectedcategory.toLowerCase()).then(data=>{
      setData(data?.data)
    });

  }, [selectedcategory])
  
  
 
  const [isActive, setActive] = useState(false);
  const handleToggle = () => {
    setActive(!isActive);
  };


  const handleClick = async (e) => {
    setData('');
    setSelectedcategory(e.target.innerHTML);
    setActive(!isActive);
  };
  
  if(!data) return <Loader/>
  return (
    <div className={styles.container}>
      <Head>
        <title>News60</title>
        <meta name="description" content="Generated by create next app" />
      
        <link rel="icon" href="/favicon.png" />
      </Head>
      <nav className={styles.navbar}>
        <div className={styles.menubtn}>
          <AiOutlineMenu onClick={handleToggle} />
        </div>
        <div
          className={`${styles.sidebar} ${
            isActive ? styles.show : styles.hide
          }`}
        >
          <span className={styles.closebtn}>
            <AiOutlineClose onClick={handleToggle} />
          </span>
          <h2>Categories</h2>
          <div className={styles.categoryList}>
            <ul>
              {categories.map((category)=>(

              <li key={category.name}
              onClick={handleClick}
              style={{backgroundColor: category.name === selectedcategory &&  "rgba(49, 118, 153, 0.463)"}}
              >
               
                {category.name}
              </li>
              ))}
            </ul>
          </div>
        </div>
        <Image
          src="/icon.png"
          width={50}
          height={50}
          className={styles.img}
          alt="Logo"
        />
        <h1>News60</h1>
      </nav>
      <main className={styles.main}>
        <h2>News Topic : <span>{selectedcategory}</span></h2>
        <div className={styles.grid}>
          
          {data?.map((news) => {
          
            return (
          
                <div className={styles.card} key={news.id}>
                  <div className={styles.imgWrapper}>
                    <img src={news.imageUrl} alt="img here"/>
                  </div>
                  <div className={styles.infowrapper}>
                    <h2>{news.title}</h2>
                    <p className={styles.author}>by {news.author}</p>
                    <p className={styles.content}>{news.content}</p>
                    <a href={news.readMoreUrl}>Read More</a>
                    <div className={styles.time}>
                      <span>
                        <img src="/date.png" alt="" className={styles.img} />
                        <p>{news.date}</p>
                      </span>
                      <span>
                        <img src="/time.png" alt="" className={styles.img} />
                        <p>{news.time}</p>
                      </span>
                    </div>
                  </div>
                </div>
              
            );
          })}

          
        </div>
      </main>

      <footer className={styles.footer}>Created By Ayush Ghiya.</footer>
    </div>
  );
}

